"""add last sample cache

Revision ID: cc5aed79e80
Revises: 43c98f7b6859
Create Date: 2015-06-09 13:37:46.447696

"""

# revision identifiers, used by Alembic.
revision = 'cc5aed79e80'
down_revision = '43c98f7b6859'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('last_samples', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'last_samples')
    ### end Alembic commands ###
