"""service id for sensors

Revision ID: 251118be576a
Revises: cc5aed79e80
Create Date: 2015-06-12 16:10:46.172591

"""

# revision identifiers, used by Alembic.
revision = '251118be576a'
down_revision = 'cc5aed79e80'
branch_labels = None
depends_on = None

from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import Integer
import sqlalchemy as sa

sensor = table('sensors', column('id', Integer))


def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('service_id', sa.String(), nullable=True))
    op.execute(sensor.delete().where(sensor.c.id==10000))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'service_id')
    ### end Alembic commands ###
