"""Added show sensor column

Revision ID: 189dabebe500
Revises: a9d60cd9728
Create Date: 2015-10-20 23:30:39.658472

"""

# revision identifiers, used by Alembic.
revision = '189dabebe500'
down_revision = 'a9d60cd9728'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('show', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'show')
    ### end Alembic commands ###
